version: '3.8'

services:
  next:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        NODE_ENV: development
    container_name: pescarte_maroon_next
    command: yarn dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/maroon
    networks:
      - pescarte
    logging:
      driver: json-file
      options:
        max-size: '50m'
        max-file: '10'

  rescript:
    build:
      context: .
      dockerfile: ./docker/rescript/Dockerfile
    container_name: pescarte_maroon_rescript
    command: yarn res:watch
    networks:
      - pescarte
    logging:
      driver: json-file
      options:
        max-size: '50m'
        max-file: '10'

networks:
  pescarte:
    external:
      name: pescarte
