#+title: Maroon
#+description: Plataforma Digital PEA Pescarte

#+caption: CI
Front end para a Plataforma Digital PEA Pescarte

-----

** Setup

*** GitHub Packages

Antes de subir o ambiente com Docker, é necessário autenticar-se no GitHub Packages. Crie um token acessando
as [[https://github.com/settings/profile][configurações do seu perfil GitHub]] > Developer Settings >
Personal Access Tokens. Para saber quais são as permissões necessárias para o token, leia a
[[https://docs.github.com/pt/packages/learn-github-packages/about-permissions-for-github-packages][documentação]]
sobre o GitHub Packages.

Após criar o token, já é possível fazer a autenticação no GitHub Packages:

#+begin_src sh
echo "<personal_token>" | docker login ghcr.io -u USERNAME --password-stdin
#+end_src

*** Requerimentos mínimos

| requirement                              | release |
|------------------------------------------+---------+
| [[https://nodejs.org/en/][nodejs]]       | 16.5.0+ |
| [[https://rescript-lang.org/][rescript]] | 9.1.4+  |
| [[https://yarnpkg.com/][yarn]]           | 1.22.5+ |

-----

** Ambiente de Desenvolvimento

*** Primeira vez rodando

É necessário construir as imagens do =Docker= ou baixá-las via =Github Packages=.

Para construí-las localmente, execute (isso levará um tempo considerável):

#+begin_src sh
docker-compose build
#+end_src

Caso queira baixar as imagena já existentes, execute:

#+begin_src sh
docker pull ghcr.io/cciuenf/pescarte_maroon_rescript:latest
#+end_src

para baixar a imagem que executa o compilador do =ReScript=, e execute:

#+begin_src sh
docker pull ghcr.io/cciuenf/pescarte_maroon_next:latest
#+end_src

que baixará a imagem que levanta o servidor web em modo de desenvolvimento.

*** Sempre que for rodar o projeto

Para iniciar o fluxo de desenvolvimento, é preciso iniciar o compilador do =ReScript= em modo de escuta e levantar o servidor web em modo de desenvolvimento. Para isso, execute:

#+begin_src sh
docker-compose up
#+end_src

Lembre-se que para esse comando funcionar, é necessário ter as imagens do =Docker= contruídas ou baixadas.

*** Para atualizar ou instalar novas dependências

Se a dependência for apenas do contexto do =NodeJS= / =NextJS=:

#+begin_src sh
docker-compose run --rm next yarn
#+end_src

Caso seja uma dependência do =ReScript=, execute o comando anterior e o seguinte:

#+begin_src sh
docker-compose run --rm rescript yarn
#+end_src

*** Portas expostas no sistema do host

Para acessar o servidor de desenvolvimento, acesse o [[http://localhost:3000][localhost]].

| container | port |
|-----------+------+
| maroon    | 3000 |

** Materiais, Tutoriais, Relatórios e extras

Todo o material do projeto (tanto backend ou frontend) pode ser encontrado no repositório [[https://github.com/cciuenf/documentos_pea_pescarte][documentos_pea_pescarte]], que abriga diversos artigos.
